package com.example.ocpspring.config;

import com.example.ocpspring.models.userspack.Role;
import com.example.ocpspring.services.UserService;
import jakarta.servlet.http.HttpServletResponse;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.context.annotation.Lazy;
import org.springframework.security.authentication.AuthenticationManager;
import org.springframework.security.authentication.ProviderManager;
import org.springframework.security.authentication.dao.DaoAuthenticationProvider;
import org.springframework.security.config.annotation.web.builders.HttpSecurity;
import org.springframework.security.config.annotation.web.configuration.EnableWebSecurity;
import org.springframework.security.config.annotation.web.configurers.AbstractHttpConfigurer;
import org.springframework.security.config.http.SessionCreationPolicy;
import org.springframework.security.core.userdetails.UserDetailsService;
import org.springframework.security.crypto.bcrypt.BCryptPasswordEncoder;
import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.security.web.AuthenticationEntryPoint;
import org.springframework.security.web.SecurityFilterChain;
import org.springframework.security.web.authentication.UsernamePasswordAuthenticationFilter;


@Configuration
@EnableWebSecurity
public class Config {

    @Autowired
    @Lazy
    private JwtRequestFilter jwtRequestFilter;

    @Bean
    public SecurityFilterChain securityFilterChain(HttpSecurity httpSecurity) throws Exception {
        httpSecurity
                .csrf(AbstractHttpConfigurer::disable)
                .authorizeHttpRequests(authorize -> authorize
                        // creation des collaborateurs pour les secretaire
                        // auto generated by controller header authorization
                        .requestMatchers("/collaborateurs/**").permitAll()
                        // service pour ADMIN
                        .requestMatchers("/services/getall", "/services/getall/**").permitAll()  // Allow access to GET methods
                        .requestMatchers("/services/**").hasAuthority("ADMIN")
                        // admin
                        .requestMatchers("/admin/change-role/**",
                                "/admin/change-service/**").hasAuthority("ADMIN")
                        .requestMatchers("/admin/**").permitAll()
                        // Authentication
                        .requestMatchers( "/auth/login",
                                "/users/secretaires").permitAll()
                        .requestMatchers( "/auth/register",
                               "/auth/users" ).hasAuthority("ADMIN")
                        // Update Garde for SECRETAIRE
                        .requestMatchers("/moderator/**").permitAll()
                        .anyRequest().permitAll()
                )
                /*
                .formLogin(formLogin -> formLogin
                        .loginPage("/login")
                        .permitAll()
                )

                 */
                .exceptionHandling(exceptionHandling -> exceptionHandling
                                .authenticationEntryPoint(customAuthenticationEntryPoint())
                )
                .sessionManagement(session -> session
                        .sessionCreationPolicy(SessionCreationPolicy.STATELESS)
                )
                .addFilterBefore(jwtRequestFilter, UsernamePasswordAuthenticationFilter.class)

                //.httpBasic(Customizer.withDefaults())
        ;
        return httpSecurity.build();
    }

    @Bean
    public AuthenticationEntryPoint customAuthenticationEntryPoint() {
        return (request, response, authException) -> {
            response.setContentType("application/json");
            response.setStatus(HttpServletResponse.SC_FORBIDDEN);
            response.getOutputStream().println("{ \"error\": \"Forbidden: Authentication is required\" }");
        };
    }
    
    @Bean
    public PasswordEncoder passwordEncoder() {
        return new BCryptPasswordEncoder();
    }

    @Bean
    public UserDetailsService userDetailsService() {
        return new UserService();
    }

    @Bean
    public AuthenticationManager authenticationManager(
            UserDetailsService userDetailsService,
            PasswordEncoder passwordEncoder) {
        DaoAuthenticationProvider authProvider = new DaoAuthenticationProvider();
        authProvider.setUserDetailsService(userDetailsService);
        authProvider.setPasswordEncoder(passwordEncoder);
        return new ProviderManager(authProvider);
    }

}
